### ISSUE TITLE
Moving cursor during proof search inserts proof into wrong place

### ISSUE THREAD

**Issue by IFcoltransG** [stepancheg/learn-idris-pub#2]
Make two holes, one of which can be solved by a proof search. Put the cursor on that hole and click Proof Search, then click the other hole before the proof search has time to finish. The proof search will complete, but will insert the found proof into the second hole rather than the first. This often doesn't typecheck and must be manually replaced (because ctrl+Z doesn't work for automatic edits such as proof searches).

**Comment by stepancheg** [comment]
Should be fixed now. Thanks!

Also, undo fixed in Chrome, but not in Firefox: I have not found how to modify textarea in Firefox [without breaking undo](https://bugzilla.mozilla.org/show_bug.cgi?id=1220696).
